### ISSUE TITLE
handling more than 200 fingerprints

### ISSUE THREAD

**Issue by thiagocaproni** [sparkfun/Fingerprint_Scanner-TTL#15]
Hello,

Is it possible to handle more than 200 fingerprints? I mean that the limitation to manipulate 200 fingerprints is related to storing or processing?
Because I want to store the fingerprints in a server. I want to use the fingerprint device only to capture the information and verify in a server if the user is registered. In this way, I could have a centralized database and interconnect several devices and I could remove its storage limitation.

Is it possible to do this?

Thanks a lot!

**Comment by JoshHawley** [comment]
The fingerprint scanner has storage for 200 fingerprints. Downloading the fingerprint templates from the FPS is possible, but downloading them to an arduino is really difficult because it does not have the memory needed to store them (even temporarily). While I'm sure that it is possible to stream the file through the arduino out to the network or other storage, it is fairly complex code that really extends beyond this library's scope.

**Comment by JoshHawley** [comment]
All that said, I do plan on looking at this issue again in the future. It is something that I want to solve so that I can make multiple FPS scanners update their local templates from a central repository.

**Comment by ahsunali** [comment]
Hi, we are experiencing the same issue, as we want to use the scanner to scan the fingerprints and store the templates in a Database , in fact the templates definitely exceeds the 200 limit, whats should be the work arround in this case ?? 
Thanks
