### ISSUE TITLE
library problem

### ISSUE THREAD

**Issue by cam2410** [sparkfun/Fingerprint_Scanner-TTL#39]
Thanks for all the hard work you must've put into this! Having a bit of an issue with the library for the FPS. Had the FPS working and had enrolled my fingerprints on the scanner. All of a sudden the thing seemed to crash and now every time I try to upload or verify the code I get the following error:

Arduino: 1.8.2 (Mac OS X), Board: "Arduino/Genuino Uno"

In file included from /Users/cameronwartnaby/Downloads/Fingerprint_Scanner-TTL-master/FPS_GT511C3/Examples/FPS_Enroll/FPS_Enroll.ino:10:0:
/Users/cameronwartnaby/Documents/Arduino/libraries/FPS_GT511C3/FPS_GT511C3.h:12:10: error: #include expects "FILENAME" or <FILENAME>
 #include "Arduino.h”;
          ^
/Users/cameronwartnaby/Documents/Arduino/libraries/FPS_GT511C3/FPS_GT511C3.h:13:10: error: #include expects "FILENAME" or <FILENAME>
 #include "SoftwareSerial.h”;
          ^
exit status 1
Error compiling for board Arduino/Genuino Uno.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

Any help would be massively appreciated! thank you

**Comment by bboyho** [comment]
Hi cam2410,

I work at SparkFun and I happened to see your issue that was posted. I didn't write the library but I have had a lot of experience with the fingerprint scanner and Hawley's Arduino library. Arduino IDE v1.6.6-v1.8.3 have bugs and differences in the way that code is compiled. If you are having issues compiling, sometimes you need to uninstall and reinstall the Arduino IDE on a computer. You can also try deleting any of your Arduino temporary files. Try using v1.8.3 or a lower version of the Arduino IDE (like v1.6.5) [ [https://www.arduino.cc/en/Main/OldSoftwareReleases#previous](https://www.arduino.cc/en/Main/OldSoftwareReleases#previous) ]. A last resort is to use Arduino v1.6.5 IDE. It might not be ideal but this was the last known stable/working IDE that I know of before all the changes. Usually this fixes the issue with different Arduino IDE versions. 

As a sanity check, I recommend checking the library on another computer to see if the Arduino IDE can compile. I've had issues where a IDE was not working on customer's laptop but it was working on his computer. There was something wrong with the settings of the computer that was preventing him from using the device. 

I tested the library on my Windows 7 64-bit computer with Arduino v.1.8.2 and v1.8.3. I did not have any issues compiling when selecting"Arduino/Genuino Uno." Since the FPS_GT511C3 Arduino library was working before, it might be a compile issue with the Arduino IDE version or the way the Arduino IDE was installed on your computer. I tried to recreate your issue with the library on one of our Mac (OSX Lion v10.7.5) testing stations. I had issues compiling the code with those versions. I had a different error but I think it had something to do with the Mac itself. Our Mac station already has issues compiling other example codes. Using v1.6.5, I had no issues compiling. 

If you have further issues, you might want to try checking or posting in the Arduino.cc forums [ [https://forum.arduino.cc/](https://forum.arduino.cc/) to see if there is someone that has more experience Mac compile errors. I believe that it has something to do with the IDE installed on your computer.
