### ISSUE TITLE
Encryption based on Template

### ISSUE THREAD

**Issue by Jakob-em** [sparkfun/Fingerprint_Scanner-TTL#56]
I would like to encrypt data based on the scanned finger. I successfully implemented the GetTemplate function but I won't get a clue about how the template stuff is working. I searched for patterns but all the templates are exactly the same and just a few bytes at the beginning are different for each finger. Any help would be appreciated.

**Comment by bboyho** [comment]
Hi,

This looks a bit old and it sounds like you are looking for technical assistance; the GitHub issues are used primarily for bugs and pull requests related to the libraries. Using the SDK, it seems that the template is supposed to be a &#42;.dat file. I do not work with those file types but it's possible that only the fingerprint scanner can understand the template since it takes three enrollments to make it.

If you have not already, you may want to post in the [SparkFun forums](https://forum.sparkfun.com/index.php) or [Arduino forums](https://forum.arduino.cc/) to see if anyone can provide some insight.
