### ISSUE TITLE
Send Fingerprint over network for verification ?

### ISSUE THREAD

**Issue by NicolaiKobras** [sparkfun/Fingerprint_Scanner-TTL#60]
I would like to use one of those modules in an authentification station on my door. My Backend Server is Python Flask and Flask_Mqtt for communication to the IOT Devices. My IOT Device is the Wemos D1 Mini based on the Esp 8266. I want to be able to send Fingerprints that are scanned to the Server, so the Server can process them.
Are any of those modules suitable for my plan, and in what format would those fingerprints be saved. Would it be hard to compare those Fingerprints Serverside ?
Thanks in advance.

**Comment by bboyho** [comment]
From the initial request, it sounds like you are looking for technical assistance; the GitHub issues are used primarily for bugs and pull requests related to the libraries. 

I have not seen that implementation before using Flask and MQTT. There were some that seem to have gotten this to working with [other languages and other development boards](https://learn.sparkfun.com/tutorials/fingerprint-scanner-gt-521fxx-hookup-guide#resources-and-going-further). However, I am not sure the exact details on how it was implemented. I believe it is possible if you are able to get the fingerprint templates. The fingerprint templates are saved as &#42;.dat files. To read, you would need to the fingerprint scanner to read the file since it created the file. I am not sure how hard that would be to compare on the server side. 

If you still need help, it would be best to check out the forums to see if anyone in the community can help you further:

* [SparkFun](https://forum.sparkfun.com/)
* [ESP8266](https://www.esp8266.com/)
* [Arduino](https://forum.arduino.cc/)
